INSERT INTO CUSTOMER(id, name, age,city) VALUES (1,'ASHUTOSH', 26,'BANGALORE');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (2,'BODHI', 26,'MUMBAI');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (3,'RANIT', 26,'GURGAON');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (4,'RAJARSHREE', 26,'KOLKATA');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (5,'ANKITA', 26,'DELHI');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (6,'ANAMIKA', 26,'HYDERABAD');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (7,'RAJESH', 26,'CHENNAI');

INSERT INTO CAR (CAR_REG_NO ,CAR_BRAND ,CAR_BRAND_MODEL ,CUSTOMER_ID ) VALUES ('KA001', 'MG HECTOR', 'SUV' , 1 );
INSERT INTO CAR (CAR_REG_NO ,CAR_BRAND ,CAR_BRAND_MODEL ,CUSTOMER_ID ) VALUES ('KA002', 'HYUNDAE', 'HATCHBACK' , 1 );
INSERT INTO CAR (CAR_REG_NO ,CAR_BRAND ,CAR_BRAND_MODEL ,CUSTOMER_ID ) VALUES ('KA003', 'MAHINDRA', 'SUV' , 2 );
INSERT INTO CAR (CAR_REG_NO ,CAR_BRAND ,CAR_BRAND_MODEL ,CUSTOMER_ID ) VALUES ('KA004', 'MERCEDEZ', 'SEDAN' , 3 );
INSERT INTO CAR (CAR_REG_NO ,CAR_BRAND ,CAR_BRAND_MODEL ,CUSTOMER_ID ) VALUES ('KA005', 'TOYOTA', 'SEDAN' , 4 );
INSERT INTO CAR (CAR_REG_NO ,CAR_BRAND ,CAR_BRAND_MODEL ,CUSTOMER_ID ) VALUES ('KA006', 'FORD', 'SUV' , 4 );
INSERT INTO CAR (CAR_REG_NO ,CAR_BRAND ,CAR_BRAND_MODEL ,CUSTOMER_ID ) VALUES ('KA007', 'TATA', 'SUV' , 1 );
