INSERT INTO CUSTOMER(id, name, age,city) VALUES (1,'ASHUTOSH', 26,'BANGALORE');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (2,'BODHI', 26,'MUMBAI');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (3,'RANIT', 26,'GURGAON');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (4,'RAJARSHREE', 26,'KOLKATA');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (5,'ANKITA', 26,'DELHI');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (6,'ANAMIKA', 26,'HYDERABAD');
INSERT INTO CUSTOMER(id, name, age,city) VALUES (7,'RAJESH', 26,'CHENNAI');